### ISSUE TITLE
Prototipação

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#1]
Imagens e, se necessário, Figma do projeto, com tela inicial e Tela de login

**Comment by Claudia-Nunes** [comment]
Boa tarde, pessoal,
Segue link, do protótipo no figma do projeto atual DTRACKER
[DTRAKER_PROTOTIPO](https://www.figma.com/file/RFp6P7vHOzIJ198IPdU1Ze/Untitled?type=design&node-id=0%3A1&mode=design&t=jHO7WTqEe7RetCzx-1)

**Comment by Claudia-Nunes** [comment]
- [x] Criado Tela de Login e anexado a tarefa de criação de Login

**Comment by Claudia-Nunes** [comment]
- [x] Criar Protótipo
- [x] Enviar para  Análise

**Comment by Claudia-Nunes** [comment]
**Tela de Login**


![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/8b107629-a715-401e-8f22-d15d33a3b04d)

**Comment by Claudia-Nunes** [comment]
**Dashboard**





![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/2464de43-1331-4619-a8fe-d61d091d491a)

**Comment by Claudia-Nunes** [comment]
**Meus Projetos**



![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/9525b74c-0985-4b34-93ab-bdf574c2536c)

**Comment by Claudia-Nunes** [comment]
**User Admin**



![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/e09c7b90-c176-4f42-a9fd-adeadb572258)
