### ISSUE TITLE
Tela de gestao

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#17]
> Tela de Administrador

Tela onde o _Gestor "pleno"_ poderá atribuir ou alterar as atribuições dos demais _gestores_ com relação aos projetos.

**Comment by itsmorais** [comment]
Entregue dia 26/04 - [781461571234de33d1a77115ac10ed94e6a7b625](https://github.com/DevsDomain/D-Traker/commit/781461571234de33d1a77115ac10ed94e6a7b625)
