### ISSUE TITLE
Barra de navegação lateral

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#18]
>  Poder acessar de maneira facil as telas:

Criar uma barra lateral de navegação para as páginas e login / logout com base no protótipo:

![Image](https://github.com/DevsDomain/D-Traker/assets/92491040/484b2c25-b48c-4933-ac7f-494466740f56)

**Comment by Jummanso** [comment]
Criada a barra com os botões (ainda sem funcionalidade nos botões devido as demais páginas não estarem criadas):

![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/7d99b340-5b0b-4f8a-83ea-81f46a931c2e)

Incorporado menu lateral na página já criada de gestão de acesso: 

![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/adc61115-8cc1-4b70-8777-39bf32f82cb5)

**Comment by fnddavi** [comment]
Trazer o código de _menu-lateral_ de _src/pages_ para _src/components_.

**Comment by Jummanso** [comment]
Alteração feita!

**Comment by Jummanso** [comment]
Inclusão caminho nos botões.
