### ISSUE TITLE
Tela login

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#2]
Desenvolver tela de login.

- [ ] Verificação com banco de usuários e validar sua "função" de gestor.

**Comment by Claudia-Nunes** [comment]
- [x] Protótipo Tela de Login, criada.
- [x] Imagem Salva na Pasta src/assets

![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/c8a596dc-751e-482b-94cc-1654a70a2192)
