### ISSUE TITLE
Tela de Admin

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#4]
Desenvolver tela de Admin.

> Visualizar os  gestores.
> Controle de acesso

![Image](https://github.com/DevsDomain/D-Traker/assets/92491040/e4f15038-8f7b-4fb1-8b80-b297217adfc2)

**Comment by Claudia-Nunes** [comment]
**Tela Admin**



![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/38120701-f8ab-4ed6-91f4-59b605dcfbc9)

**Comment by itsmorais** [comment]
Página gestão de acesso criada!
3 Componentes criados [TabelaGestores, Pesquisa, Select]
Funcionalidades de filtro concluídas.
Aguardando Banco de dados para executar funcionalidade de conceder ou remover acesso

![image](https://github.com/DevsDomain/D-Traker/assets/53665466/9550a02d-f72e-41ee-9f43-3f3964429f0c)
