### ISSUE TITLE
Criar tela "meus projetos"

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#5]
> 

![Image](https://github.com/DevsDomain/D-Traker/assets/92491040/b822c730-c57c-4205-9767-70cca591044b)

![Image](https://github.com/DevsDomain/D-Traker/assets/92491040/7ae1bb3b-dc2b-4249-8b5d-e5dd00f9e258)

**Comment by Claudia-Nunes** [comment]
**Tela Meus projetos**



![Image](https://github.com/DevsDomain/D-Traker/assets/104475381/1657725e-bc8a-4ea3-b3d0-dca588c6d594)

**Comment by Jummanso** [comment]
Aguardando retorno @fnddavi e @abnercosta97 validadando protótipo com a cliente para dar sequência na atividade.

**Comment by fnddavi** [comment]
Tarefa concluída sem ter sido realizada devido ao atraso das informações vindas dos clientes (BD e validação de prototipo)
