### ISSUE TITLE
Correção da imagem - Login

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#56]
Correção da imagem da tela de login.

**Comment by Jummanso** [comment]
Tela de login alterada:
![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/bde6a291-7428-4435-899c-5afd18ea10ca)
![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/b3ad066b-a233-42e6-b083-02f97ed54ba3)
![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/fda3fcb7-b148-4a8b-9eb3-e897e7a31f2e)

Tela de login antiga:
![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/4228a684-b09f-4b56-8ad7-334979fe8fcf)

**Comment by itsmorais** [comment]
Feito
