### ISSUE TITLE
Filtro Projeto - Dashboard

### ISSUE THREAD

**Issue by fnddavi** [DevsDomain/D-Traker#58]
Filtro Projeto
- Ligar banco de dados no filtro na tela do Dahboard

**Comment by Jummanso** [comment]
Criado type projetos.ts

![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/6fdb76ce-6035-461d-ba5a-f65ef297843a)

Colocado o console.log na linha 22 para testar se os dados estão sendo puxados:

![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/24194a1d-32cb-4556-acbd-cf0a48f6ea42)

verificação dos dados sendo puxados corretamente na linha 22:

![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/00f250c2-3e0f-436d-ad1f-5e3a1fec2ba2)
