### ISSUE TITLE
Cards para Dashboard - New Tasks

### ISSUE THREAD

**Issue by Jummanso** [DevsDomain/D-Traker#78]

**Comment by Jummanso** [comment]
Fazer o componente New Tasks, colocá-lo na tela de Dashboard e fazer a interação com o banco de dados.

![Image](https://github.com/DevsDomain/D-Traker/assets/126696706/08067c9c-aa75-4191-bf7b-12792e905521)

**Comment by ghost** [comment]
Inserido campo Total tasks:
![Image](https://github.com/DevsDomain/D-Traker/assets/171388155/97f9f1fd-905f-4289-937a-53bbd3a138bd)
Feito ligação com o banco de dados:
![Image](https://github.com/DevsDomain/D-Traker/assets/171388155/38b61c0c-e1f6-4c14-8403-cf1d13c5b879)
![Image](https://github.com/DevsDomain/D-Traker/assets/171388155/1b1496fc-edef-423a-991a-9881e5ec695b)
![Image](https://github.com/DevsDomain/D-Traker/assets/171388155/ab25c6d1-db28-49d0-80f3-d026d0c45731)

**Comment by itsmorais** [comment]
Funcionando!
